[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
runTask = { id = "xyz.jpenilla.run-velocity", version = "3.1.0" }

[versions]
java = "25"
kotlin = "2.4.20"
shadow = "9.6.1"
velocity = "4.2.0"
floodgate = "2.2.5-SNAPSHOT"

[libraries]
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
floodgate-api = { module = "org.geysermc.floodgate:api", version.ref = "floodgate" }
toml4j = { module = "com.moandjiezana.toml:toml4j", version = "0.7.2" }
